### ISSUE TITLE
Draggable marker with updating current location 

### ISSUE THREAD

**Issue by morad00** [apptreesoftware/flutter_map#81]
* Can a marker be draggable? 
* How to update my current location ?
* Can I add ModalBottomSheet widget or somthing that display the current address to the user ?

**Comment by johnpryan** [comment]
see https://github.com/apptreesoftware/flutter_map/issues/21#issuecomment-394422192 for info about draggable markers.

Location management is a different package: https://pub.dartlang.org/packages/location.  You can render the location using a Marker.

Since this is a normal flutter widget, you can add any other widgets you like

**Comment by klaszlo8207** [comment]
Any example on this? Hoiw to drag my locations marker?

**Comment by klaszlo8207** [comment]
> 
> 
> see https://github.com/apptreesoftware/flutter_map/issues/21#issuecomment-394422192 for info about draggable markers.
> 
> Location management is a different package: https://pub.dartlang.org/packages/location. You can render the location using a Marker.
> 
> Since this is a normal flutter widget, you can add any other widgets you like

that is a 404 error

**Any example on this? How to drag my location's marker?**

**Comment by ibrierley** [comment]
You can access the original comment now at https://github.com/johnpryan/flutter_map/issues/21#issuecomment-394422192

**Comment by klaszlo8207** [comment]
So it is not implemented yet, thanks
